version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - jenkins_home:/var/jenkins_home
      - "${MONEY_SERVICES_ROOT}:/moneyservices"
      - ./_volumes/ssh/:/var/jenkins_home/.ssh
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.constraint-label=traefik_net"
      - "traefik.http.routers.jenkins.rule=Host(\"${JENKINS_HOST}\")"
      - "traefik.http.routers.jenkins.entrypoints=http"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    networks:
      traefik_network:

  ssh-agent:
    image: jenkins/ssh-agent

volumes:
  jenkins_home:

networks:
  traefik_network:
    name: traefik_net
    external: true